# Generated by Django 4.1.2 on 2022-10-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('desc', models.TextField(null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
